version: '3.4'

services:
  catalogdb:
   image: postgres

  basketdb:
   image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  distributedcache:
    image: redis

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount/Discount.grpc/Dockerfile

volumes:
 postgres_catalog:
 postgres_basket:



